#!/bin/sh

session_name='floaterm'
width='60%'
height='70%'

if [ "$(tmux display-message -p '#S')" = "$session_name" ]; then
  tmux detach
else
  tmux popup -B -E -w $width -h $height \
    "tmux attach -t $session_name || tmux new -s $session_name"
fi
