#!/usr/bin/env bash

# Start fzf in a Zellij floating pane.
# Based on: https://github.com/junegunn/fzf/blob/master/bin/fzf-tmux

fail() {
   >&2 echo "$1"
   exit 2
}

help() {
   cat <<'EOF'
Usage: fzf-zellij [FZF OPTIONS]

Options:
   -h, --help         Display this message.

Environment variables:
   FZF_ZELLIJ_HEIGHT  Pane height (integer or percentage)
   FZF_ZELLIJ_WIDTH   Pane width (integer or percentage)
   FZF_ZELLIJ_X       X coordinate (integer or percentage)
   FZF_ZELLIJ_Y       Y coordinate (integer or percentage)
   FZF_ZELLIJ_NAME    Pane name (default: fzf)
   FZF_ZELLIJ_PINNED  Whether the pane is pinned (default: true)

   Each environment variable FZF_ZELLIJ_{NAME} corresponds to `zellij run --{name}`.
EOF
}

for arg in "$@"; do
   case "${arg}" in
      -h|--help)
         help
         exit 0
         ;;
   esac
done

fzf="$(command which fzf)"
[[ -x ${fzf} ]] || fail 'fzf executable not found.'

if [[ -z "${ZELLIJ:-}" ]]; then
   "${fzf}" "$@"
   exit $?
fi

zellij="$(command which zellij)"
[[ -x ${zellij} ]] || fail 'zellij executable not found.'

args=("$@" '--no-height' '--no-tmux' '--bind=ctrl-z:ignore')

id="${RANDOM}"
tmpdir="${TMPDIR:-/tmp}"
argsf="${tmpdir}/fzf-zellij-args-${id}"
fifo_in="${tmpdir}/fzf-zellij-fifo-in-${id}"
fifo_out="${tmpdir}/fzf-zellij-fifo-out-${id}"
fifo_code="${tmpdir}/fzf-zellij-fifo-code-${id}"

cleanup() {
   if [[ -n ${pane_pid} ]]; then
      kill -SIGUSR1 ${pane_pid} 2>/dev/null
   fi
   pkill -SIGUSR1 -P ${pppid} 2>/dev/null
   \rm -f "${argsf}" "${fifo_in}" "${fifo_out}" "${fifo_code}"
   if [[ $# -gt 0 ]]; then
      trap - EXIT
      exit 130
   fi
}
trap 'cleanup 1' SIGUSR1
trap 'cleanup' EXIT

envs="export TERM=${TERM} "
envs="${envs} FZF_DEFAULT_COMMAND=$(printf %q "${FZF_DEFAULT_COMMAND}")"
envs="${envs} FZF_DEFAULT_OPTS=$(printf %q "${FZF_DEFAULT_OPTS}")"
envs="${envs} FZF_DEFAULT_OPTS_FILE=$(printf %q "${FZF_DEFAULT_OPTS_FILE}")"
[[ -n $RUNEWIDTH_EASTASIAN ]] && envs="${envs} RUNEWIDTH_EASTASIAN=$(printf %q "${RUNEWIDTH_EASTASIAN}")"
[[ -n $BAT_THEME ]] && envs="${envs} BAT_THEME=$(printf %q "${BAT_THEME}")"
echo "${envs};" > "${argsf}"

opts=$(printf "%q " "${args[@]}")

pppid=$$
echo -n "trap 'kill -SIGUSR1 ${pppid}' EXIT SIGINT SIGTERM;" >> "${argsf}"
close="; trap - EXIT SIGINT SIGTERM"

mkfifo -m o+w "${fifo_out}"
mkfifo -m o+w "${fifo_code}"

if [[ -t 0 ]]; then
   cat <<< "\"${fzf}\" ${opts} > \"${fifo_out}\"; echo \$? > \"${fifo_code}\" ${close}" >> "${argsf}"
else
   mkfifo "${fifo_in}"
   cat <<< "\"${fzf}\" ${opts} < \"${fifo_in}\" > \"${fifo_out}\"; echo \$? > \"${fifo_code}\" ${close}" >> "${argsf}"
   cat <&0 > "${fifo_in}" &
fi

fz_height="${FZF_ZELLIJ_HEIGHT:+--height=${FZF_ZELLIJ_HEIGHT}}"
fz_width="${FZF_ZELLIJ_WIDTH:+--width=${FZF_ZELLIJ_WIDTH}}"
fz_x="${FZF_ZELLIJ_X:+--x=${FZF_ZELLIJ_X}}"
fz_y="${FZF_ZELLIJ_Y:+--y=${FZF_ZELLIJ_Y}}"
fz_name="${FZF_ZELLIJ_NAME:-fzf}"
fz_pinned="${FZF_ZELLIJ_PINNED:-true}"

"${zellij}" run --floating --close-on-exit --pinned="${fz_pinned}" --name="${fz_name}" ${fz_height} ${fz_width} ${fz_x} ${fz_y} -- bash "${argsf}"

pane_pid=$(pgrep -f -x "bash ${argsf}" -o)
if [[ -z ${pane_pid} ]]; then
   cleanup 1
fi

cat "${fifo_out}"
exit "$(cat "${fifo_code}")"
