#!/bin/bash

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null)
TEMPLATE_FILE="$REPO_ROOT/.gitmessage"
COMMIT_MSG_FILE=$1

if [ -f "$TEMPLATE_FILE" ]; then
  if [ -z "$2" ]; then
    TEMP_MSG=$(mktemp)
    echo "" >"$TEMP_MSG"
    cat "$TEMPLATE_FILE" >>"$TEMP_MSG"
    sed '1,3d' "$COMMIT_MSG_FILE" >>"$TEMP_MSG"
    mv "$TEMP_MSG" "$COMMIT_MSG_FILE"
  fi
fi
