#!/bin/sh

vendor=$(lscpu | grep "Vendor ID" | awk '{print $3}')

if echo "$vendor" | grep -q 'AMD'; then
  temperature=$(sensors | grep "Tctl:" | tr -d '+' | awk '{print $2}' | sed 's/°C//g')

elif echo "$vendor" | grep -q 'Intel'; then
  temperature=$(sensors | grep "Package id 0:" | tr -d '+' | awk '{print $4}' | sed 's/°C//g')
else
  exit 1
fi

if awk "BEGIN {exit !($temperature >= 75.0)}"; then
  class="critical"
else
  class="normal"
fi

echo "{ \"text\": \"$temperature\", \"class\": \"$class\"}"
