#!/bin/sh

yabai -m config layout bsp
yabai -m config window_placement second_child

yabai -m config window_opacity on
yabai -m config active_window_opacity 0.980000
yabai -m config normal_window_opacity 0.890000

yabai -m config window_gap 8
yabai -m config top_padding 8
yabai -m config right_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8

yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add title="^Settings$" manage=off
yabai -m rule --add app="KakaoTalk" manage=off

yabai -m rule --add app="Finder" manage=off
yabai -m rule --add app="Spotify" manage=off
yabai -m rule --add app="1Password" manage=off
yabai -m rule --add app="Alfred*" manage=off
yabai -m rule --add app="ChatGPT" manage=off

# Jetbrains
yabai -m rule --add title="Rename" manage=off
yabai -m rule --add title="Move" manage=off
yabai -m rule --add title="Delete" manage=off
yabai -m rule --add title="Add File to Git" manage=off

yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action stack

yabai -m config insert_feedback_color 0x000000ff

# Automatically focus wezterm windows opened with hotkey
yabai -m signal \
  --add event="window_created" \
  app="(.*WezTerm.*|.*wezterm.*)" \
  action="yabai -m window \$YABAI_WINDOW_ID --focus"

# focus window after active space changes
yabai -m signal \
  --add event=space_changed \
  action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# focus window after active display changes
yabai -m signal \
  --add \
  event=display_changed \
  action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

[ -f "$HOME/.config/yabai/yabairc_mutable" ] && . "$HOME/.config/yabai/yabairc_mutable"
