#!/bin/sh

selected=$( \
  tmux ls -f '#{&&:#{!=:#{session_name},scratch},#{==:#{session_attached},0}}' \
    | awk '{ print substr($1, 0, length($1) - 1) }' \
    | fzf-tmux \
      -p20%,20% \
      --preview ''
)

if [[ -z $selected ]]; then
  exit 0
fi

tmux switch -t "$selected"
